version: '2'
services:
  rabbit1:
    image: deadtrickster/rabbitmq_prometheus
    hostname: rabbit1
    expose:
      - "9090"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  rabbit2:
    image: rabbitmq:3.7.2-management
    hostname: rabbit2
    links:
      - rabbit1
    environment: 
     - CLUSTERED=true
     - CLUSTER_WITH=rabbit1
     - RAM_NODE=true
    ports:
        - "5673:5672"
        - "15673:15672"

  rabbit3:
    image: rabbitmq:3.7.2-management
    hostname: rabbit3
    links:
      - rabbit1
      - rabbit2
    environment: 
     - CLUSTERED=true
     - CLUSTER_WITH=rabbit1
    ports:
          - "5674:5672"
